/**
 * Scoped visual identity for the Routing Lab. Namespaced under
 * .rlab-shell so nothing leaks into other shells. The direction is an
 * instrumentation bench: near-black chrome, a rose accent for stress,
 * signal-green for clean quality readings, and monospace numerals for
 * the metric readouts (the point of the surface is the numbers).
 */
export const ROUTING_STYLES = `
.rlab-shell {
  --rl-bg: #0b0f16;
  --rl-panel: #121826;
  --rl-panel-2: #0e1420;
  --rl-line: #253048;
  --rl-ink: #d6deeb;
  --rl-ink-dim: #7e8ca3;
  --rl-rose: #fb7185;
  --rl-green: #4ade80;
  --rl-amber: #fbbf24;
  --rl-cyan: #38bdf8;
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  background: var(--rl-bg);
  color: var(--rl-ink);
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
}
.rlab-mono { font-family: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, monospace; }

.rlab-topbar {
  display: flex; align-items: center; gap: 16px;
  height: 48px; padding: 0 14px; flex: 0 0 auto;
  background: linear-gradient(180deg, #141b2b, #0e1420);
  border-bottom: 1px solid var(--rl-line);
}
.rlab-back {
  background: transparent; color: var(--rl-ink-dim);
  border: 1px solid var(--rl-line); border-radius: 6px;
  padding: 5px 10px; font-size: 12px; cursor: pointer;
}
.rlab-back:hover { color: var(--rl-ink); border-color: var(--rl-rose); }
.rlab-wordmark { display: flex; flex-direction: column; line-height: 1.15; }
.rlab-wordmark b { font-size: 13px; letter-spacing: 0.02em; }
.rlab-wordmark span { font-size: 10.5px; color: var(--rl-ink-dim); letter-spacing: 0.14em; text-transform: uppercase; }
.rlab-title { margin-left: auto; font-size: 13px; display: flex; align-items: center; gap: 10px; }
.rlab-badge {
  font-size: 10px; font-weight: 700; letter-spacing: 0.08em;
  padding: 2px 8px; border-radius: 9999px;
  background: rgba(251, 113, 133, 0.15); color: var(--rl-rose);
  border: 1px solid rgba(251, 113, 133, 0.35);
}

.rlab-body { flex: 1 1 auto; display: flex; min-height: 0; }

.rlab-sidebar {
  flex: 0 0 250px; display: flex; flex-direction: column; min-height: 0;
  background: var(--rl-panel-2); border-right: 1px solid var(--rl-line);
  overflow-y: auto;
}
.rlab-panel-head {
  flex: 0 0 auto; padding: 10px 12px 6px; font-size: 10.5px; font-weight: 700;
  letter-spacing: 0.14em; text-transform: uppercase; color: var(--rl-ink-dim);
}
.rlab-scenario {
  display: block; width: calc(100% - 16px); margin: 0 8px 6px; text-align: left;
  background: var(--rl-panel); color: var(--rl-ink);
  border: 1px solid var(--rl-line); border-left: 3px solid transparent;
  border-radius: 6px; padding: 9px 10px; cursor: pointer; font: inherit;
}
.rlab-scenario:hover { border-color: var(--rl-rose); }
.rlab-scenario.rlab-active { border-left-color: var(--rl-rose); background: #182034; }
.rlab-scenario b { display: block; font-size: 12.5px; }
.rlab-scenario span { display: block; font-size: 11px; color: var(--rl-ink-dim); margin-top: 2px; line-height: 1.35; }

.rlab-canvas-wrap { flex: 1 1 auto; display: flex; flex-direction: column; min-width: 0; }
.rlab-toolbar {
  flex: 0 0 auto; display: flex; align-items: center; gap: 14px;
  padding: 7px 12px; border-bottom: 1px solid var(--rl-line);
  background: var(--rl-panel-2); font-size: 12px; color: var(--rl-ink-dim);
}
.rlab-toolbar label { margin-right: 4px; }
.rlab-toolbar select {
  background: var(--rl-panel); color: var(--rl-ink);
  border: 1px solid var(--rl-line); border-radius: 5px;
  padding: 3px 6px; font-size: 12px;
}
.rlab-toolbar input[type="checkbox"] { accent-color: var(--rl-cyan); vertical-align: middle; }
.rlab-toolbar-engine { flex-wrap: wrap; row-gap: 4px; }
.rlab-toolbar-tag {
  font-size: 10px; letter-spacing: 0.12em; color: var(--rl-ink-dim);
  border: 1px solid var(--rl-line); border-radius: 4px; padding: 2px 6px;
}
.rlab-canvas-host { flex: 1 1 auto; position: relative; min-height: 0; }
.rlab-canvas-host > div { position: absolute; inset: 0; }

/* A9 hover trace: holding the pointer on an edge isolates it (all
   other edges fade) and thickens it, so one line stays followable
   through a crossing storm. Pure CSS over the view's data-ssv-*
   contract; the pinned-trace variant is generated by the shell. */
.rlab-canvas-host svg g[data-ssv-edge] path {
  transition: opacity 90ms linear, stroke-width 90ms linear;
}
.rlab-canvas-host svg:has(g[data-ssv-edge]:hover) g[data-ssv-edge]:not(:hover) path {
  opacity: 0.15;
}
.rlab-canvas-host svg g[data-ssv-edge]:hover path[data-ssv-edge-path] {
  stroke-width: 3;
}
.rlab-empty {
  position: absolute; inset: 0; display: flex; align-items: center;
  justify-content: center; color: var(--rl-ink-dim); font-size: 13px;
}

.rlab-inspector {
  flex: 0 0 272px; display: flex; flex-direction: column; min-height: 0;
  background: var(--rl-panel-2); border-left: 1px solid var(--rl-line);
  overflow-y: auto;
}
.rlab-section { padding: 4px 12px 12px; font-size: 12px; line-height: 1.5; color: var(--rl-ink); }
.rlab-section p { margin: 0 0 8px; color: var(--rl-ink-dim); }
.rlab-stress { margin: 0; padding-left: 16px; color: var(--rl-ink-dim); }
.rlab-stress li { margin-bottom: 3px; }

.rlab-metric-row {
  display: flex; justify-content: space-between; align-items: baseline;
  padding: 4px 0; border-bottom: 1px solid var(--rl-line);
}
.rlab-metric-row:last-child { border-bottom: none; }
.rlab-metric-label { color: var(--rl-ink-dim); font-size: 11.5px; }
.rlab-metric-value { font-size: 13px; font-weight: 600; }
.rlab-ok { color: var(--rl-green); }
.rlab-warn { color: var(--rl-amber); }
.rlab-bad { color: var(--rl-rose); }
`;
