/**
 * A PROV-O style provenance record for the auditor (item 3). Entities
 * (artifacts) are generated by activities, activities are associated with
 * agents, and entities are derived from earlier entities, forming an audit
 * chain from draft requirements through analysis, test, review, and approval.
 * Each activity and entity carries timestamps, which the timeline and the
 * range slider read. The build also materializes an `attributed` flag on each
 * entity (whether it has any provenance link) so a node-local SHACL shape can
 * flag orphan artifacts, and the fixture seeds a few real audit defects: an
 * approval with no generation time, an activity that never recorded an end,
 * and a legacy spec with no provenance at all.
 */
import { UGM } from "@g3t/core";

interface AgentRec {
  id: string;
  name: string;
  role: string;
}
interface ActivityRec {
  id: string;
  name: string;
  started?: string;
  ended?: string;
  agent: string;
}
interface EntityRec {
  id: string;
  name: string;
  generated?: string;
  generatedBy?: string;
  derivedFrom?: string;
}

const agents: AgentRec[] = [
  { id: "agent:alice", name: "Alice Chen", role: "Systems Engineer" },
  { id: "agent:ci", name: "CI Pipeline", role: "Automated" },
  { id: "agent:bob", name: "Bob Ruiz", role: "Reviewer" },
  { id: "agent:carol", name: "Carol Ng", role: "Approver" },
];

const activities: ActivityRec[] = [
  {
    id: "act:draft",
    name: "Draft requirements",
    started: "2025-01-10T08:00:00Z",
    ended: "2025-01-15T17:00:00Z",
    agent: "agent:alice",
  },
  {
    id: "act:analyze",
    name: "Run analysis",
    started: "2025-01-20T09:00:00Z",
    ended: "2025-02-01T17:00:00Z",
    agent: "agent:ci",
  },
  {
    id: "act:test",
    name: "Execute tests",
    started: "2025-02-20T09:00:00Z",
    ended: "2025-03-01T18:00:00Z",
    agent: "agent:ci",
  },
  {
    id: "act:review",
    name: "Peer review",
    started: "2025-03-05T09:00:00Z",
    ended: "2025-03-12T16:00:00Z",
    agent: "agent:bob",
  },
  {
    id: "act:hazard",
    name: "Hazard analysis",
    started: "2025-01-25T09:00:00Z",
    ended: "2025-02-05T17:00:00Z",
    agent: "agent:alice",
  },
  {
    id: "act:safety-review",
    name: "Safety review",
    started: "2025-02-10T09:00:00Z",
    ended: "2025-02-14T15:00:00Z",
    agent: "agent:bob",
  },
  {
    id: "act:regress",
    name: "Regression run",
    started: "2025-03-15T06:00:00Z",
    ended: "2025-03-15T09:00:00Z",
    agent: "agent:ci",
  },
  // No end time recorded: an incomplete audit record (warning).
  {
    id: "act:approve",
    name: "Approve release",
    started: "2025-04-01T10:00:00Z",
    agent: "agent:carol",
  },
];

const entities: EntityRec[] = [
  {
    id: "ent:reqs",
    name: "Requirements v1",
    generated: "2025-01-15T17:00:00Z",
    generatedBy: "act:draft",
  },
  {
    id: "ent:analysis",
    name: "Analysis report",
    generated: "2025-02-01T17:00:00Z",
    generatedBy: "act:analyze",
    derivedFrom: "ent:reqs",
  },
  {
    id: "ent:tests",
    name: "Test results",
    generated: "2025-03-01T18:00:00Z",
    generatedBy: "act:test",
    derivedFrom: "ent:analysis",
  },
  {
    id: "ent:review",
    name: "Review record",
    generated: "2025-03-12T16:00:00Z",
    generatedBy: "act:review",
    derivedFrom: "ent:tests",
  },
  // No generation time recorded: a provenance gap (violation).
  {
    id: "ent:release",
    name: "Signed approval",
    generatedBy: "act:approve",
    derivedFrom: "ent:review",
  },
  {
    id: "ent:hazards",
    name: "Hazard log",
    generated: "2025-02-05T17:00:00Z",
    generatedBy: "act:hazard",
    derivedFrom: "ent:reqs",
  },
  {
    id: "ent:safety",
    name: "Safety case",
    generated: "2025-02-14T15:00:00Z",
    generatedBy: "act:safety-review",
    derivedFrom: "ent:hazards",
  },
  {
    id: "ent:regress",
    name: "Regression evidence",
    generated: "2025-03-15T09:00:00Z",
    generatedBy: "act:regress",
    derivedFrom: "ent:tests",
  },
  // No generatedBy and no derivedFrom: an orphan artifact (warning).
  { id: "ent:legacy", name: "Legacy spec", generated: "2025-01-05T00:00:00Z" },
];

const uses: Array<{ activity: string; entity: string }> = [
  { activity: "act:analyze", entity: "ent:reqs" },
  { activity: "act:test", entity: "ent:analysis" },
  { activity: "act:review", entity: "ent:tests" },
  { activity: "act:review", entity: "ent:safety" },
  { activity: "act:approve", entity: "ent:review" },
  { activity: "act:hazard", entity: "ent:reqs" },
  { activity: "act:safety-review", entity: "ent:hazards" },
  { activity: "act:regress", entity: "ent:tests" },
];

export function buildProvenance(): UGM {
  const ugm = new UGM();

  for (const a of agents) {
    ugm.addNode(a.id, {
      types: ["Agent"],
      properties: { name: a.name, role: a.role },
    });
  }
  for (const act of activities) {
    const properties: Record<string, unknown> = { name: act.name };
    if (act.started) properties.startedAtTime = act.started;
    if (act.ended) properties.endedAtTime = act.ended;
    ugm.addNode(act.id, { types: ["Activity"], properties });
    ugm.addEdge(act.id, act.agent, {
      type: "wasAssociatedWith",
      confidence: 1,
    });
  }
  for (const e of entities) {
    const attributed = Boolean(e.generatedBy || e.derivedFrom);
    const properties: Record<string, unknown> = { name: e.name, attributed };
    if (e.generated) properties.generatedAtTime = e.generated;
    ugm.addNode(e.id, { types: ["Entity"], properties });
    if (e.generatedBy)
      ugm.addEdge(e.id, e.generatedBy, {
        type: "wasGeneratedBy",
        confidence: 1,
      });
    if (e.derivedFrom)
      ugm.addEdge(e.id, e.derivedFrom, {
        type: "wasDerivedFrom",
        confidence: 1,
      });
  }
  for (const u of uses) {
    ugm.addEdge(u.activity, u.entity, { type: "used", confidence: 1 });
  }

  return ugm;
}
